"""initial schema (baseline from models)

Revision ID: 0001
Revises:
Create Date: 2026-06-06

This baseline creates every table from the SQLAlchemy models' metadata, so it
always matches the ORM definitions. For an EXISTING database that already has
the tables (created by the app's startup bootstrap), run:

    alembic stamp head

to mark the schema as up-to-date without re-creating anything. Future schema
changes should be added as new autogenerated revisions:

    alembic revision --autogenerate -m "describe change"
"""
from typing import Sequence, Union

from app.database.base import Base

# Import the models so their tables register on Base.metadata.
from app.models import auth_user  # noqa: F401
from app.models import auth_user_dataset_link  # noqa: F401
from app.models import auth_user_preference  # noqa: F401
from app.models import business  # noqa: F401
from app.models import review  # noqa: F401
from app.models import user  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
